export const LOGIN_CHANGE = "LOGIN_CHANGE";
export const SIGNUP_CHANGE = "SIGNUP_CHANGE";

export const AUTH_START = "AUTH_START";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_PROVIDER = "LOGIN_PROVIDER";
export const SIGNIN_USER = "SIGNIN_USER";
export const SIGNIN_PROVIDER = "SIGNIN_PROVIDER";

export const GET_AUTH_DATA = "GET_AUTH_DATA";

export const ONCLICKACCOUNTMENU = "ONCLICKACCOUNTMENU";
export const TOGGLESIDEBARMENU = "TOGGLESIDEBARMENU";
